### ISSUE TITLE
error: ‘FLT_MAX’ was not declared in this scope

### ISSUE THREAD

**Issue by vanniktech** [BSVino/MathForGameDevelopers#1]
When I execute make on my Ubuntu machine I get the following error:

```
g++  -std=c++0x -I. -Icommon -Imath -Iinclude -c game/character.cpp -o game/character.o
In file included from game/game.h:26:0,
                 from game/character.h:18,
                 from game/character.cpp:18:
./math/graph.h: In constructor ‘CGraph::CNode::CNode()’:
./math/graph.h:28:17: error: ‘FLT_MAX’ was not declared in this scope
    path_weight= FLT_MAX;
                 ^
make: *** [game/character.o] Error 1
```

Do you happen to know where FLT_MAX comes frome?

**Comment by BSVino** [comment]
Sorry about that, I don't always test the Linux build. Does #include <cmath> work?

**Comment by BSVino** [comment]
Strike that, looks like you need <cfloat> or <float.h>

http://www.cplusplus.com/reference/cfloat/

**Comment by vanniktech** [comment]
After adding `#include "float.h"` and removing the `#ifdef _WIN32` check in `main.cpp` for `#include "sys/timeb.h"` I get the following error:

```
g++ -Llib -o mfgd common/platform_linux.o datamanager/data.o datamanager/dataserializer.o game/character.o game/game.o game/handle.o game/main.o math/collision.o math/color.o math/euler.o math/frustum.o math/matrix.o math/quaternion.o math/vector.o math/graph.o renderer/application.o renderer/image_read.o renderer/renderer.o renderer/renderingcontext.o renderer/shaders.o  renderer/gl3w.o  -lglfw -lXrandr -lGL 
/usr/bin/ld: common/platform_linux.o: undefined reference to symbol 'XGetWindowAttributes'
//usr/lib/x86_64-linux-gnu/libX11.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [mfgd] Error 1
```

**Comment by BSVino** [comment]
Try adding -LX11 to the makefile?

**Comment by vanniktech** [comment]
After adding some other stuff too I finally got it working and now have a mfgd file. If I try to execute it (`./mfgd`) nothing happens though. Do I need to give the program some kind of special command line argument?

**Comment by BSVino** [comment]
No you shouldn't have to pass any arguments. Does it hang or immediately return?

You've caught me at a weird time because I'm between builds of my main computer and I don't have access to Linux at the moment.

**Comment by vanniktech** [comment]
No worries. At first I though, it just simply does not run at all. After I have waited for about 35 seconds I got this back:

```
Highest score: 2147469247
Insertion sort time: 32988ms
Highest score: 2147469247
Heap sort time: 73ms
```

Looks like it's running one of the tests and not the game.

**Comment by BSVino** [comment]
Ah! The latest sources don't produce a window, they just run an algorithm and compare. Try checking out the sources specific to the video you're interested in. Each video where I do a code section should have an associated label in the github repo.
