### ISSUE TITLE
Quaternion multiplication

### ISSUE THREAD

**Issue by Icesory** [BSVino/MathForGameDevelopers#2]
in line
https://github.com/BSVino/MathForGameDevelopers/blob/quaternion-transform/math/quaternion.cpp#L34
you have write '+' but in your video 
https://youtu.be/Ne3RNhEVSIE?t=7m23s
you have an pop up, which says it should be an '-'
So what is right?

Accordingly to an other library it should be really an - sign. 

```
    Quaternion getProduct(Quaternion q) {
      // Quaternion multiplication is defined by:
      //     (Q1 * Q2).w = (w1w2 - x1x2 - y1y2 - z1z2)
      //     (Q1 * Q2).x = (w1x2 + x1w2 + y1z2 - z1y2)
      //     (Q1 * Q2).y = (w1y2 - x1z2 + y1w2 + z1x2)
      //     (Q1 * Q2).z = (w1z2 + x1y2 - y1x2 + z1w2
      return Quaternion(
               w * q.w - x * q.x - y * q.y - z * q.z, // new w
               w * q.x + x * q.w + y * q.z - z * q.y, // new x
               w * q.y - x * q.z + y * q.w + z * q.x, // new y
               w * q.z + x * q.y - y * q.x + z * q.w); // new z
    }
```

**Comment by BSVino** [comment]
Good observation. I fixed this issue at one point, I just neglected to merge it into the branch you mentioned. Looks like it's fixed in master: https://github.com/BSVino/MathForGameDevelopers/blob/master/math/quaternion.cpp#L30

**Comment by Icesory** [comment]
have not seen that this isnt the master branch. but this branch is linked in the Youtube video.

Anyway, can you help me with an special quaternion rotation?  eventually per Email?

**Comment by BSVino** [comment]
Yea I really need to update this branch.

I'll try to assist you if you're having trouble with the math but I can't help you debug a specific problem. My email is bs.vino@gmail.com
