### ISSUE TITLE
game/main.h update wrong for gravity?

### ISSUE THREAD

**Issue by wirecat** [BSVino/MathForGameDevelopers#4]
I believe in [game/main.h:53](https://github.com/BSVino/MathForGameDevelopers/blob/optimization-pipeline/game/main.h#l53) the formula may be wrong. I think the line should read:
`p->m_velocity = p->m_velocity + g_gravity * g_frame_time;`
I feel like the equation doesn't make sense without the frame time multiplication because you end up adding mixed units(m/s + m/s^2).

I'm really curious if that is the case or if I'm missing something here.

**Edit:** I forgot to say that I love your videos! They have been very informative and have already helped me improve some of my production code. Thank you for doing them and please continue to do them!

**Comment by BSVino** [comment]
Yea that would definitely be wrong. This code was about demonstrating the processor pipeline so it appears I was careless about the physics part of things. Good catch. :)
